export * from "./structs.ts";

// Autogenerated API file for BatchV1
import * as c from "../../common.ts";
import * as operations from "../../operations.ts";
import * as MetaV1 from "../meta@v1/structs.ts";
import * as BatchV1 from "./structs.ts";

export class BatchV1Api {
  #client: c.RestClient;
  #root = "/apis/batch/v1/";
  constructor(client: c.RestClient) {
    this.#client = client;
  }

  namespace(name: string) {
    return new BatchV1NamespacedApi(this.#client, name);
  }
  myNamespace() {
    if (!this.#client.defaultNamespace) throw new Error("No current namespace is set");
    return new BatchV1NamespacedApi(this.#client, this.#client.defaultNamespace);
  }

  async getJobListForAllNamespaces(opts: operations.GetListOpts = {}) {
    const resp = await this.#client.performRequest({
      method: "GET",
      path: `${this.#root}jobs`,
      expectJson: true,
      querystring: operations.formatGetListOpts(opts),
      abortSignal: opts.abortSignal,
    });
    return BatchV1.toJobList(resp);
  }

  async watchJobListForAllNamespaces(opts: operations.WatchListOpts = {}) {
    const resp = await this.#client.performRequest({
      method: "GET",
      path: `${this.#root}jobs`,
      expectJson: true,
      expectStream: true,
      querystring: operations.formatWatchListOpts(opts),
      abortSignal: opts.abortSignal,
    });
    return resp.pipeThrough(new c.WatchEventTransformer(BatchV1.toJob, MetaV1.toStatus));
  }

}

export class BatchV1NamespacedApi {
  #client: c.RestClient
  #root: string
  constructor(client: c.RestClient, namespace: string) {
    this.#client = client;
    this.#root = `/apis/batch/v1/namespaces/${namespace}/`;
  }

  async getJobList(opts: operations.GetListOpts = {}) {
    const resp = await this.#client.performRequest({
      method: "GET",
      path: `${this.#root}jobs`,
      expectJson: true,
      querystring: operations.formatGetListOpts(opts),
      abortSignal: opts.abortSignal,
    });
    return BatchV1.toJobList(resp);
  }

  async watchJobList(opts: operations.WatchListOpts = {}) {
    const resp = await this.#client.performRequest({
      method: "GET",
      path: `${this.#root}jobs`,
      expectJson: true,
      expectStream: true,
      querystring: operations.formatWatchListOpts(opts),
      abortSignal: opts.abortSignal,
    });
    return resp.pipeThrough(new c.WatchEventTransformer(BatchV1.toJob, MetaV1.toStatus));
  }

  async createJob(body: BatchV1.Job, opts: operations.PutOpts = {}) {
    const resp = await this.#client.performRequest({
      method: "POST",
      path: `${this.#root}jobs`,
      expectJson: true,
      querystring: operations.formatPutOpts(opts),
      bodyJson: BatchV1.fromJob(body),
      abortSignal: opts.abortSignal,
    });
    return BatchV1.toJob(resp);
  }

  async deleteJobList(opts: operations.DeleteListOpts = {}) {
    const resp = await this.#client.performRequest({
      method: "DELETE",
      path: `${this.#root}jobs`,
      expectJson: true,
      querystring: operations.formatDeleteListOpts(opts),
      abortSignal: opts.abortSignal,
    });
    return BatchV1.toJobList(resp);
  }

  async getJob(name: string, opts: operations.NoOpts = {}) {
    const resp = await this.#client.performRequest({
      method: "GET",
      path: `${this.#root}jobs/${name}`,
      expectJson: true,
      abortSignal: opts.abortSignal,
    });
    return BatchV1.toJob(resp);
  }

  async deleteJob(name: string, opts: operations.DeleteOpts = {}) {
    const resp = await this.#client.performRequest({
      method: "DELETE",
      path: `${this.#root}jobs/${name}`,
      expectJson: true,
      querystring: operations.formatDeleteOpts(opts),
      abortSignal: opts.abortSignal,
    });
    return BatchV1.toJob(resp);
  }

  async replaceJob(name: string, body: BatchV1.Job, opts: operations.PutOpts = {}) {
    const resp = await this.#client.performRequest({
      method: "PUT",
      path: `${this.#root}jobs/${name}`,
      expectJson: true,
      querystring: operations.formatPutOpts(opts),
      bodyJson: BatchV1.fromJob(body),
      abortSignal: opts.abortSignal,
    });
    return BatchV1.toJob(resp);
  }

  async patchJob(name: string, type: c.PatchType, body: BatchV1.Job | c.JsonPatch, opts: operations.PatchOpts = {}) {
    const resp = await this.#client.performRequest({
      method: "PATCH",
      path: `${this.#root}jobs/${name}`,
      expectJson: true,
      querystring: operations.formatPatchOpts(opts),
      contentType: c.getPatchContentType(type),
      bodyJson: Array.isArray(body) ? body : BatchV1.fromJob(body),
      abortSignal: opts.abortSignal,
    });
    return BatchV1.toJob(resp);
  }

  async getJobStatus(name: string, opts: operations.NoOpts = {}) {
    const resp = await this.#client.performRequest({
      method: "GET",
      path: `${this.#root}jobs/${name}/status`,
      expectJson: true,
      abortSignal: opts.abortSignal,
    });
    return BatchV1.toJob(resp);
  }

  async replaceJobStatus(name: string, body: BatchV1.Job, opts: operations.PutOpts = {}) {
    const resp = await this.#client.performRequest({
      method: "PUT",
      path: `${this.#root}jobs/${name}/status`,
      expectJson: true,
      querystring: operations.formatPutOpts(opts),
      bodyJson: BatchV1.fromJob(body),
      abortSignal: opts.abortSignal,
    });
    return BatchV1.toJob(resp);
  }

  async patchJobStatus(name: string, type: c.PatchType, body: BatchV1.Job | c.JsonPatch, opts: operations.PatchOpts = {}) {
    const resp = await this.#client.performRequest({
      method: "PATCH",
      path: `${this.#root}jobs/${name}/status`,
      expectJson: true,
      querystring: operations.formatPatchOpts(opts),
      contentType: c.getPatchContentType(type),
      bodyJson: Array.isArray(body) ? body : BatchV1.fromJob(body),
      abortSignal: opts.abortSignal,
    });
    return BatchV1.toJob(resp);
  }

}
