export * from "./structs.ts";

// Autogenerated API file for ResourceV1alpha1
import * as c from "../../common.ts";
import * as operations from "../../operations.ts";
import * as MetaV1 from "../meta@v1/structs.ts";
import * as ResourceV1alpha1 from "./structs.ts";

export class ResourceV1alpha1Api {
  #client: c.RestClient;
  #root = "/apis/resource.k8s.io/v1alpha1/";
  constructor(client: c.RestClient) {
    this.#client = client;
  }

  namespace(name: string) {
    return new ResourceV1alpha1NamespacedApi(this.#client, name);
  }
  myNamespace() {
    if (!this.#client.defaultNamespace) throw new Error("No current namespace is set");
    return new ResourceV1alpha1NamespacedApi(this.#client, this.#client.defaultNamespace);
  }

  async getPodSchedulingListForAllNamespaces(opts: operations.GetListOpts = {}) {
    const resp = await this.#client.performRequest({
      method: "GET",
      path: `${this.#root}podschedulings`,
      expectJson: true,
      querystring: operations.formatGetListOpts(opts),
      abortSignal: opts.abortSignal,
    });
    return ResourceV1alpha1.toPodSchedulingList(resp);
  }

  async watchPodSchedulingListForAllNamespaces(opts: operations.WatchListOpts = {}) {
    const resp = await this.#client.performRequest({
      method: "GET",
      path: `${this.#root}podschedulings`,
      expectJson: true,
      expectStream: true,
      querystring: operations.formatWatchListOpts(opts),
      abortSignal: opts.abortSignal,
    });
    return resp.pipeThrough(new c.WatchEventTransformer(ResourceV1alpha1.toPodScheduling, MetaV1.toStatus));
  }

  async getResourceClaimListForAllNamespaces(opts: operations.GetListOpts = {}) {
    const resp = await this.#client.performRequest({
      method: "GET",
      path: `${this.#root}resourceclaims`,
      expectJson: true,
      querystring: operations.formatGetListOpts(opts),
      abortSignal: opts.abortSignal,
    });
    return ResourceV1alpha1.toResourceClaimList(resp);
  }

  async watchResourceClaimListForAllNamespaces(opts: operations.WatchListOpts = {}) {
    const resp = await this.#client.performRequest({
      method: "GET",
      path: `${this.#root}resourceclaims`,
      expectJson: true,
      expectStream: true,
      querystring: operations.formatWatchListOpts(opts),
      abortSignal: opts.abortSignal,
    });
    return resp.pipeThrough(new c.WatchEventTransformer(ResourceV1alpha1.toResourceClaim, MetaV1.toStatus));
  }

  async getResourceClaimTemplateListForAllNamespaces(opts: operations.GetListOpts = {}) {
    const resp = await this.#client.performRequest({
      method: "GET",
      path: `${this.#root}resourceclaimtemplates`,
      expectJson: true,
      querystring: operations.formatGetListOpts(opts),
      abortSignal: opts.abortSignal,
    });
    return ResourceV1alpha1.toResourceClaimTemplateList(resp);
  }

  async watchResourceClaimTemplateListForAllNamespaces(opts: operations.WatchListOpts = {}) {
    const resp = await this.#client.performRequest({
      method: "GET",
      path: `${this.#root}resourceclaimtemplates`,
      expectJson: true,
      expectStream: true,
      querystring: operations.formatWatchListOpts(opts),
      abortSignal: opts.abortSignal,
    });
    return resp.pipeThrough(new c.WatchEventTransformer(ResourceV1alpha1.toResourceClaimTemplate, MetaV1.toStatus));
  }

  async getResourceClassList(opts: operations.GetListOpts = {}) {
    const resp = await this.#client.performRequest({
      method: "GET",
      path: `${this.#root}resourceclasses`,
      expectJson: true,
      querystring: operations.formatGetListOpts(opts),
      abortSignal: opts.abortSignal,
    });
    return ResourceV1alpha1.toResourceClassList(resp);
  }

  async watchResourceClassList(opts: operations.WatchListOpts = {}) {
    const resp = await this.#client.performRequest({
      method: "GET",
      path: `${this.#root}resourceclasses`,
      expectJson: true,
      expectStream: true,
      querystring: operations.formatWatchListOpts(opts),
      abortSignal: opts.abortSignal,
    });
    return resp.pipeThrough(new c.WatchEventTransformer(ResourceV1alpha1.toResourceClass, MetaV1.toStatus));
  }

  async createResourceClass(body: ResourceV1alpha1.ResourceClass, opts: operations.PutOpts = {}) {
    const resp = await this.#client.performRequest({
      method: "POST",
      path: `${this.#root}resourceclasses`,
      expectJson: true,
      querystring: operations.formatPutOpts(opts),
      bodyJson: ResourceV1alpha1.fromResourceClass(body),
      abortSignal: opts.abortSignal,
    });
    return ResourceV1alpha1.toResourceClass(resp);
  }

  async deleteResourceClassList(opts: operations.DeleteListOpts = {}) {
    const resp = await this.#client.performRequest({
      method: "DELETE",
      path: `${this.#root}resourceclasses`,
      expectJson: true,
      querystring: operations.formatDeleteListOpts(opts),
      abortSignal: opts.abortSignal,
    });
    return ResourceV1alpha1.toResourceClassList(resp);
  }

  async getResourceClass(name: string, opts: operations.NoOpts = {}) {
    const resp = await this.#client.performRequest({
      method: "GET",
      path: `${this.#root}resourceclasses/${name}`,
      expectJson: true,
      abortSignal: opts.abortSignal,
    });
    return ResourceV1alpha1.toResourceClass(resp);
  }

  async deleteResourceClass(name: string, opts: operations.DeleteOpts = {}) {
    const resp = await this.#client.performRequest({
      method: "DELETE",
      path: `${this.#root}resourceclasses/${name}`,
      expectJson: true,
      querystring: operations.formatDeleteOpts(opts),
      abortSignal: opts.abortSignal,
    });
    if (c.isStatusKind(resp)) return MetaV1.toStatus(resp);
    return ResourceV1alpha1.toResourceClass(resp);
  }

  async replaceResourceClass(name: string, body: ResourceV1alpha1.ResourceClass, opts: operations.PutOpts = {}) {
    const resp = await this.#client.performRequest({
      method: "PUT",
      path: `${this.#root}resourceclasses/${name}`,
      expectJson: true,
      querystring: operations.formatPutOpts(opts),
      bodyJson: ResourceV1alpha1.fromResourceClass(body),
      abortSignal: opts.abortSignal,
    });
    return ResourceV1alpha1.toResourceClass(resp);
  }

  async patchResourceClass(name: string, type: c.PatchType, body: ResourceV1alpha1.ResourceClass | c.JsonPatch, opts: operations.PatchOpts = {}) {
    const resp = await this.#client.performRequest({
      method: "PATCH",
      path: `${this.#root}resourceclasses/${name}`,
      expectJson: true,
      querystring: operations.formatPatchOpts(opts),
      contentType: c.getPatchContentType(type),
      bodyJson: Array.isArray(body) ? body : ResourceV1alpha1.fromResourceClass(body),
      abortSignal: opts.abortSignal,
    });
    return ResourceV1alpha1.toResourceClass(resp);
  }

}

export class ResourceV1alpha1NamespacedApi {
  #client: c.RestClient
  #root: string
  constructor(client: c.RestClient, namespace: string) {
    this.#client = client;
    this.#root = `/apis/resource.k8s.io/v1alpha1/namespaces/${namespace}/`;
  }

  async getPodSchedulingList(opts: operations.GetListOpts = {}) {
    const resp = await this.#client.performRequest({
      method: "GET",
      path: `${this.#root}podschedulings`,
      expectJson: true,
      querystring: operations.formatGetListOpts(opts),
      abortSignal: opts.abortSignal,
    });
    return ResourceV1alpha1.toPodSchedulingList(resp);
  }

  async watchPodSchedulingList(opts: operations.WatchListOpts = {}) {
    const resp = await this.#client.performRequest({
      method: "GET",
      path: `${this.#root}podschedulings`,
      expectJson: true,
      expectStream: true,
      querystring: operations.formatWatchListOpts(opts),
      abortSignal: opts.abortSignal,
    });
    return resp.pipeThrough(new c.WatchEventTransformer(ResourceV1alpha1.toPodScheduling, MetaV1.toStatus));
  }

  async createPodScheduling(body: ResourceV1alpha1.PodScheduling, opts: operations.PutOpts = {}) {
    const resp = await this.#client.performRequest({
      method: "POST",
      path: `${this.#root}podschedulings`,
      expectJson: true,
      querystring: operations.formatPutOpts(opts),
      bodyJson: ResourceV1alpha1.fromPodScheduling(body),
      abortSignal: opts.abortSignal,
    });
    return ResourceV1alpha1.toPodScheduling(resp);
  }

  async deletePodSchedulingList(opts: operations.DeleteListOpts = {}) {
    const resp = await this.#client.performRequest({
      method: "DELETE",
      path: `${this.#root}podschedulings`,
      expectJson: true,
      querystring: operations.formatDeleteListOpts(opts),
      abortSignal: opts.abortSignal,
    });
    return ResourceV1alpha1.toPodSchedulingList(resp);
  }

  async getPodScheduling(name: string, opts: operations.NoOpts = {}) {
    const resp = await this.#client.performRequest({
      method: "GET",
      path: `${this.#root}podschedulings/${name}`,
      expectJson: true,
      abortSignal: opts.abortSignal,
    });
    return ResourceV1alpha1.toPodScheduling(resp);
  }

  async deletePodScheduling(name: string, opts: operations.DeleteOpts = {}) {
    const resp = await this.#client.performRequest({
      method: "DELETE",
      path: `${this.#root}podschedulings/${name}`,
      expectJson: true,
      querystring: operations.formatDeleteOpts(opts),
      abortSignal: opts.abortSignal,
    });
    if (c.isStatusKind(resp)) return MetaV1.toStatus(resp);
    return ResourceV1alpha1.toPodScheduling(resp);
  }

  async replacePodScheduling(name: string, body: ResourceV1alpha1.PodScheduling, opts: operations.PutOpts = {}) {
    const resp = await this.#client.performRequest({
      method: "PUT",
      path: `${this.#root}podschedulings/${name}`,
      expectJson: true,
      querystring: operations.formatPutOpts(opts),
      bodyJson: ResourceV1alpha1.fromPodScheduling(body),
      abortSignal: opts.abortSignal,
    });
    return ResourceV1alpha1.toPodScheduling(resp);
  }

  async patchPodScheduling(name: string, type: c.PatchType, body: ResourceV1alpha1.PodScheduling | c.JsonPatch, opts: operations.PatchOpts = {}) {
    const resp = await this.#client.performRequest({
      method: "PATCH",
      path: `${this.#root}podschedulings/${name}`,
      expectJson: true,
      querystring: operations.formatPatchOpts(opts),
      contentType: c.getPatchContentType(type),
      bodyJson: Array.isArray(body) ? body : ResourceV1alpha1.fromPodScheduling(body),
      abortSignal: opts.abortSignal,
    });
    return ResourceV1alpha1.toPodScheduling(resp);
  }

  async getPodSchedulingStatus(name: string, opts: operations.NoOpts = {}) {
    const resp = await this.#client.performRequest({
      method: "GET",
      path: `${this.#root}podschedulings/${name}/status`,
      expectJson: true,
      abortSignal: opts.abortSignal,
    });
    return ResourceV1alpha1.toPodScheduling(resp);
  }

  async replacePodSchedulingStatus(name: string, body: ResourceV1alpha1.PodScheduling, opts: operations.PutOpts = {}) {
    const resp = await this.#client.performRequest({
      method: "PUT",
      path: `${this.#root}podschedulings/${name}/status`,
      expectJson: true,
      querystring: operations.formatPutOpts(opts),
      bodyJson: ResourceV1alpha1.fromPodScheduling(body),
      abortSignal: opts.abortSignal,
    });
    return ResourceV1alpha1.toPodScheduling(resp);
  }

  async patchPodSchedulingStatus(name: string, type: c.PatchType, body: ResourceV1alpha1.PodScheduling | c.JsonPatch, opts: operations.PatchOpts = {}) {
    const resp = await this.#client.performRequest({
      method: "PATCH",
      path: `${this.#root}podschedulings/${name}/status`,
      expectJson: true,
      querystring: operations.formatPatchOpts(opts),
      contentType: c.getPatchContentType(type),
      bodyJson: Array.isArray(body) ? body : ResourceV1alpha1.fromPodScheduling(body),
      abortSignal: opts.abortSignal,
    });
    return ResourceV1alpha1.toPodScheduling(resp);
  }

  async getResourceClaimList(opts: operations.GetListOpts = {}) {
    const resp = await this.#client.performRequest({
      method: "GET",
      path: `${this.#root}resourceclaims`,
      expectJson: true,
      querystring: operations.formatGetListOpts(opts),
      abortSignal: opts.abortSignal,
    });
    return ResourceV1alpha1.toResourceClaimList(resp);
  }

  async watchResourceClaimList(opts: operations.WatchListOpts = {}) {
    const resp = await this.#client.performRequest({
      method: "GET",
      path: `${this.#root}resourceclaims`,
      expectJson: true,
      expectStream: true,
      querystring: operations.formatWatchListOpts(opts),
      abortSignal: opts.abortSignal,
    });
    return resp.pipeThrough(new c.WatchEventTransformer(ResourceV1alpha1.toResourceClaim, MetaV1.toStatus));
  }

  async createResourceClaim(body: ResourceV1alpha1.ResourceClaim, opts: operations.PutOpts = {}) {
    const resp = await this.#client.performRequest({
      method: "POST",
      path: `${this.#root}resourceclaims`,
      expectJson: true,
      querystring: operations.formatPutOpts(opts),
      bodyJson: ResourceV1alpha1.fromResourceClaim(body),
      abortSignal: opts.abortSignal,
    });
    return ResourceV1alpha1.toResourceClaim(resp);
  }

  async deleteResourceClaimList(opts: operations.DeleteListOpts = {}) {
    const resp = await this.#client.performRequest({
      method: "DELETE",
      path: `${this.#root}resourceclaims`,
      expectJson: true,
      querystring: operations.formatDeleteListOpts(opts),
      abortSignal: opts.abortSignal,
    });
    return ResourceV1alpha1.toResourceClaimList(resp);
  }

  async getResourceClaim(name: string, opts: operations.NoOpts = {}) {
    const resp = await this.#client.performRequest({
      method: "GET",
      path: `${this.#root}resourceclaims/${name}`,
      expectJson: true,
      abortSignal: opts.abortSignal,
    });
    return ResourceV1alpha1.toResourceClaim(resp);
  }

  async deleteResourceClaim(name: string, opts: operations.DeleteOpts = {}) {
    const resp = await this.#client.performRequest({
      method: "DELETE",
      path: `${this.#root}resourceclaims/${name}`,
      expectJson: true,
      querystring: operations.formatDeleteOpts(opts),
      abortSignal: opts.abortSignal,
    });
    if (c.isStatusKind(resp)) return MetaV1.toStatus(resp);
    return ResourceV1alpha1.toResourceClaim(resp);
  }

  async replaceResourceClaim(name: string, body: ResourceV1alpha1.ResourceClaim, opts: operations.PutOpts = {}) {
    const resp = await this.#client.performRequest({
      method: "PUT",
      path: `${this.#root}resourceclaims/${name}`,
      expectJson: true,
      querystring: operations.formatPutOpts(opts),
      bodyJson: ResourceV1alpha1.fromResourceClaim(body),
      abortSignal: opts.abortSignal,
    });
    return ResourceV1alpha1.toResourceClaim(resp);
  }

  async patchResourceClaim(name: string, type: c.PatchType, body: ResourceV1alpha1.ResourceClaim | c.JsonPatch, opts: operations.PatchOpts = {}) {
    const resp = await this.#client.performRequest({
      method: "PATCH",
      path: `${this.#root}resourceclaims/${name}`,
      expectJson: true,
      querystring: operations.formatPatchOpts(opts),
      contentType: c.getPatchContentType(type),
      bodyJson: Array.isArray(body) ? body : ResourceV1alpha1.fromResourceClaim(body),
      abortSignal: opts.abortSignal,
    });
    return ResourceV1alpha1.toResourceClaim(resp);
  }

  async getResourceClaimStatus(name: string, opts: operations.NoOpts = {}) {
    const resp = await this.#client.performRequest({
      method: "GET",
      path: `${this.#root}resourceclaims/${name}/status`,
      expectJson: true,
      abortSignal: opts.abortSignal,
    });
    return ResourceV1alpha1.toResourceClaim(resp);
  }

  async replaceResourceClaimStatus(name: string, body: ResourceV1alpha1.ResourceClaim, opts: operations.PutOpts = {}) {
    const resp = await this.#client.performRequest({
      method: "PUT",
      path: `${this.#root}resourceclaims/${name}/status`,
      expectJson: true,
      querystring: operations.formatPutOpts(opts),
      bodyJson: ResourceV1alpha1.fromResourceClaim(body),
      abortSignal: opts.abortSignal,
    });
    return ResourceV1alpha1.toResourceClaim(resp);
  }

  async patchResourceClaimStatus(name: string, type: c.PatchType, body: ResourceV1alpha1.ResourceClaim | c.JsonPatch, opts: operations.PatchOpts = {}) {
    const resp = await this.#client.performRequest({
      method: "PATCH",
      path: `${this.#root}resourceclaims/${name}/status`,
      expectJson: true,
      querystring: operations.formatPatchOpts(opts),
      contentType: c.getPatchContentType(type),
      bodyJson: Array.isArray(body) ? body : ResourceV1alpha1.fromResourceClaim(body),
      abortSignal: opts.abortSignal,
    });
    return ResourceV1alpha1.toResourceClaim(resp);
  }

  async getResourceClaimTemplateList(opts: operations.GetListOpts = {}) {
    const resp = await this.#client.performRequest({
      method: "GET",
      path: `${this.#root}resourceclaimtemplates`,
      expectJson: true,
      querystring: operations.formatGetListOpts(opts),
      abortSignal: opts.abortSignal,
    });
    return ResourceV1alpha1.toResourceClaimTemplateList(resp);
  }

  async watchResourceClaimTemplateList(opts: operations.WatchListOpts = {}) {
    const resp = await this.#client.performRequest({
      method: "GET",
      path: `${this.#root}resourceclaimtemplates`,
      expectJson: true,
      expectStream: true,
      querystring: operations.formatWatchListOpts(opts),
      abortSignal: opts.abortSignal,
    });
    return resp.pipeThrough(new c.WatchEventTransformer(ResourceV1alpha1.toResourceClaimTemplate, MetaV1.toStatus));
  }

  async createResourceClaimTemplate(body: ResourceV1alpha1.ResourceClaimTemplate, opts: operations.PutOpts = {}) {
    const resp = await this.#client.performRequest({
      method: "POST",
      path: `${this.#root}resourceclaimtemplates`,
      expectJson: true,
      querystring: operations.formatPutOpts(opts),
      bodyJson: ResourceV1alpha1.fromResourceClaimTemplate(body),
      abortSignal: opts.abortSignal,
    });
    return ResourceV1alpha1.toResourceClaimTemplate(resp);
  }

  async deleteResourceClaimTemplateList(opts: operations.DeleteListOpts = {}) {
    const resp = await this.#client.performRequest({
      method: "DELETE",
      path: `${this.#root}resourceclaimtemplates`,
      expectJson: true,
      querystring: operations.formatDeleteListOpts(opts),
      abortSignal: opts.abortSignal,
    });
    return ResourceV1alpha1.toResourceClaimTemplateList(resp);
  }

  async getResourceClaimTemplate(name: string, opts: operations.NoOpts = {}) {
    const resp = await this.#client.performRequest({
      method: "GET",
      path: `${this.#root}resourceclaimtemplates/${name}`,
      expectJson: true,
      abortSignal: opts.abortSignal,
    });
    return ResourceV1alpha1.toResourceClaimTemplate(resp);
  }

  async deleteResourceClaimTemplate(name: string, opts: operations.DeleteOpts = {}) {
    const resp = await this.#client.performRequest({
      method: "DELETE",
      path: `${this.#root}resourceclaimtemplates/${name}`,
      expectJson: true,
      querystring: operations.formatDeleteOpts(opts),
      abortSignal: opts.abortSignal,
    });
    if (c.isStatusKind(resp)) return MetaV1.toStatus(resp);
    return ResourceV1alpha1.toResourceClaimTemplate(resp);
  }

  async replaceResourceClaimTemplate(name: string, body: ResourceV1alpha1.ResourceClaimTemplate, opts: operations.PutOpts = {}) {
    const resp = await this.#client.performRequest({
      method: "PUT",
      path: `${this.#root}resourceclaimtemplates/${name}`,
      expectJson: true,
      querystring: operations.formatPutOpts(opts),
      bodyJson: ResourceV1alpha1.fromResourceClaimTemplate(body),
      abortSignal: opts.abortSignal,
    });
    return ResourceV1alpha1.toResourceClaimTemplate(resp);
  }

  async patchResourceClaimTemplate(name: string, type: c.PatchType, body: ResourceV1alpha1.ResourceClaimTemplate | c.JsonPatch, opts: operations.PatchOpts = {}) {
    const resp = await this.#client.performRequest({
      method: "PATCH",
      path: `${this.#root}resourceclaimtemplates/${name}`,
      expectJson: true,
      querystring: operations.formatPatchOpts(opts),
      contentType: c.getPatchContentType(type),
      bodyJson: Array.isArray(body) ? body : ResourceV1alpha1.fromResourceClaimTemplate(body),
      abortSignal: opts.abortSignal,
    });
    return ResourceV1alpha1.toResourceClaimTemplate(resp);
  }

}
