export * from "./structs.ts";

// Autogenerated API file for NodeV1
import * as c from "../../common.ts";
import * as operations from "../../operations.ts";
import * as MetaV1 from "../meta@v1/structs.ts";
import * as NodeV1 from "./structs.ts";

export class NodeV1Api {
  #client: c.RestClient;
  #root = "/apis/node.k8s.io/v1/";
  constructor(client: c.RestClient) {
    this.#client = client;
  }

  async getRuntimeClassList(opts: operations.GetListOpts = {}): Promise<NodeV1.RuntimeClassList> {
    const resp = await this.#client.performRequest({
      method: "GET",
      path: `${this.#root}runtimeclasses`,
      expectJson: true,
      querystring: operations.formatGetListOpts(opts),
      abortSignal: opts.abortSignal,
    });
    return NodeV1.toRuntimeClassList(resp);
  }

  async watchRuntimeClassList(opts: operations.WatchListOpts = {}): Promise<ReadableStream<c.WatchEvent<NodeV1.RuntimeClass & c.ApiKind, MetaV1.Status & c.ApiKind>>> {
    const resp = await this.#client.performRequest({
      method: "GET",
      path: `${this.#root}runtimeclasses`,
      expectJson: true,
      expectStream: true,
      querystring: operations.formatWatchListOpts(opts),
      abortSignal: opts.abortSignal,
    });
    return resp.pipeThrough(new c.WatchEventTransformer(NodeV1.toRuntimeClass, MetaV1.toStatus));
  }

  async createRuntimeClass(body: NodeV1.RuntimeClass, opts: operations.PutOpts = {}): Promise<NodeV1.RuntimeClass> {
    const resp = await this.#client.performRequest({
      method: "POST",
      path: `${this.#root}runtimeclasses`,
      expectJson: true,
      querystring: operations.formatPutOpts(opts),
      bodyJson: NodeV1.fromRuntimeClass(body),
      abortSignal: opts.abortSignal,
    });
    return NodeV1.toRuntimeClass(resp);
  }

  async deleteRuntimeClassList(opts: operations.DeleteListOpts = {}): Promise<NodeV1.RuntimeClassList> {
    const resp = await this.#client.performRequest({
      method: "DELETE",
      path: `${this.#root}runtimeclasses`,
      expectJson: true,
      querystring: operations.formatDeleteListOpts(opts),
      abortSignal: opts.abortSignal,
    });
    return NodeV1.toRuntimeClassList(resp);
  }

  async getRuntimeClass(name: string, opts: operations.NoOpts = {}): Promise<NodeV1.RuntimeClass> {
    const resp = await this.#client.performRequest({
      method: "GET",
      path: `${this.#root}runtimeclasses/${name}`,
      expectJson: true,
      abortSignal: opts.abortSignal,
    });
    return NodeV1.toRuntimeClass(resp);
  }

  async deleteRuntimeClass(name: string, opts: operations.DeleteOpts = {}): Promise<NodeV1.RuntimeClass | MetaV1.Status> {
    const resp = await this.#client.performRequest({
      method: "DELETE",
      path: `${this.#root}runtimeclasses/${name}`,
      expectJson: true,
      querystring: operations.formatDeleteOpts(opts),
      abortSignal: opts.abortSignal,
    });
    if (c.isStatusKind(resp)) return MetaV1.toStatus(resp);
    return NodeV1.toRuntimeClass(resp);
  }

  async replaceRuntimeClass(name: string, body: NodeV1.RuntimeClass, opts: operations.PutOpts = {}): Promise<NodeV1.RuntimeClass> {
    const resp = await this.#client.performRequest({
      method: "PUT",
      path: `${this.#root}runtimeclasses/${name}`,
      expectJson: true,
      querystring: operations.formatPutOpts(opts),
      bodyJson: NodeV1.fromRuntimeClass(body),
      abortSignal: opts.abortSignal,
    });
    return NodeV1.toRuntimeClass(resp);
  }

  async patchRuntimeClass(name: string, type: c.PatchType, body: NodeV1.RuntimeClass | c.JsonPatch, opts: operations.PatchOpts = {}): Promise<NodeV1.RuntimeClass> {
    const resp = await this.#client.performRequest({
      method: "PATCH",
      path: `${this.#root}runtimeclasses/${name}`,
      expectJson: true,
      querystring: operations.formatPatchOpts(opts),
      contentType: c.getPatchContentType(type),
      bodyJson: Array.isArray(body) ? body : NodeV1.fromRuntimeClass(body),
      abortSignal: opts.abortSignal,
    });
    return NodeV1.toRuntimeClass(resp);
  }

}
