// Autogenerated Schema file for CertificatesV1alpha1
import * as c from "../../common.ts";

import * as MetaV1 from "../meta@v1/structs.ts";
type ListOf<T> = {
  metadata: MetaV1.ListMeta;
  items: Array<T>;
};

/** ClusterTrustBundle is a cluster-scoped container for X.509 trust anchors (root certificates).

ClusterTrustBundle objects are considered to be readable by any authenticated user in the cluster, because they can be mounted by pods using the `clusterTrustBundle` projection.  All service accounts have read access to ClusterTrustBundles by default.  Users who only have namespace-level access to a cluster can read ClusterTrustBundles by impersonating a serviceaccount that they have access to.

It can be optionally associated with a particular assigner, in which case it contains one valid set of trust anchors for that signer. Signers may have multiple associated ClusterTrustBundles; each is an independent set of trust anchors for that signer. Admission control is used to enforce that only users with permissions on the signer can create or modify the corresponding bundle. */
export interface ClusterTrustBundle {
  apiVersion?: "certificates.k8s.io/v1alpha1";
  kind?: "ClusterTrustBundle";
  metadata?: MetaV1.ObjectMeta | null;
  spec: ClusterTrustBundleSpec;
}
export function toClusterTrustBundle(input: c.JSONValue): ClusterTrustBundle & c.ApiKind {
  const obj = c.checkObj(input);
  return {
    ...c.assertOrAddApiVersionAndKind(obj, "certificates.k8s.io/v1alpha1", "ClusterTrustBundle"),
    metadata: c.readOpt(obj["metadata"], MetaV1.toObjectMeta),
    spec: toClusterTrustBundleSpec(obj["spec"]),
  }}
export function fromClusterTrustBundle(input: ClusterTrustBundle): c.JSONValue {
  return {
    ...c.assertOrAddApiVersionAndKind(input, "certificates.k8s.io/v1alpha1", "ClusterTrustBundle"),
    ...input,
    metadata: input.metadata != null ? MetaV1.fromObjectMeta(input.metadata) : undefined,
    spec: input.spec != null ? fromClusterTrustBundleSpec(input.spec) : undefined,
  }}

/** ClusterTrustBundleSpec contains the signer and trust anchors. */
export interface ClusterTrustBundleSpec {
  signerName?: string | null;
  trustBundle: string;
}
export function toClusterTrustBundleSpec(input: c.JSONValue): ClusterTrustBundleSpec {
  const obj = c.checkObj(input);
  return {
    signerName: c.readOpt(obj["signerName"], c.checkStr),
    trustBundle: c.checkStr(obj["trustBundle"]),
  }}
export function fromClusterTrustBundleSpec(input: ClusterTrustBundleSpec): c.JSONValue {
  return {
    ...input,
  }}

/** ClusterTrustBundleList is a collection of ClusterTrustBundle objects */
export interface ClusterTrustBundleList extends ListOf<ClusterTrustBundle> {
  apiVersion?: "certificates.k8s.io/v1alpha1";
  kind?: "ClusterTrustBundleList";
};
export function toClusterTrustBundleList(input: c.JSONValue): ClusterTrustBundleList & c.ApiKind {
  const obj = c.checkObj(input);
  return {
    ...c.assertOrAddApiVersionAndKind(obj, "certificates.k8s.io/v1alpha1", "ClusterTrustBundleList"),
    metadata: MetaV1.toListMeta(obj.metadata),
    items: c.readList(obj.items, toClusterTrustBundle),
  }}
