// Autogenerated Schema file for CoordinationV1
import * as c from "../../common.ts";

import * as MetaV1 from "../meta@v1/structs.ts";
type ListOf<T> = {
  metadata: MetaV1.ListMeta;
  items: Array<T>;
};

/** Lease defines a lease concept. */
export interface Lease {
  apiVersion?: "coordination.k8s.io/v1";
  kind?: "Lease";
  metadata?: MetaV1.ObjectMeta | null;
  spec?: LeaseSpec | null;
}
export function toLease(input: c.JSONValue): Lease & c.ApiKind {
  const obj = c.checkObj(input);
  return {
    ...c.assertOrAddApiVersionAndKind(obj, "coordination.k8s.io/v1", "Lease"),
    metadata: c.readOpt(obj["metadata"], MetaV1.toObjectMeta),
    spec: c.readOpt(obj["spec"], toLeaseSpec),
  }}
export function fromLease(input: Lease): c.JSONValue {
  return {
    ...c.assertOrAddApiVersionAndKind(input, "coordination.k8s.io/v1", "Lease"),
    ...input,
    metadata: input.metadata != null ? MetaV1.fromObjectMeta(input.metadata) : undefined,
    spec: input.spec != null ? fromLeaseSpec(input.spec) : undefined,
  }}

/** LeaseSpec is a specification of a Lease. */
export interface LeaseSpec {
  acquireTime?: c.MicroTime | null;
  holderIdentity?: string | null;
  leaseDurationSeconds?: number | null;
  leaseTransitions?: number | null;
  renewTime?: c.MicroTime | null;
}
export function toLeaseSpec(input: c.JSONValue): LeaseSpec {
  const obj = c.checkObj(input);
  return {
    acquireTime: c.readOpt(obj["acquireTime"], c.toMicroTime),
    holderIdentity: c.readOpt(obj["holderIdentity"], c.checkStr),
    leaseDurationSeconds: c.readOpt(obj["leaseDurationSeconds"], c.checkNum),
    leaseTransitions: c.readOpt(obj["leaseTransitions"], c.checkNum),
    renewTime: c.readOpt(obj["renewTime"], c.toMicroTime),
  }}
export function fromLeaseSpec(input: LeaseSpec): c.JSONValue {
  return {
    ...input,
    acquireTime: input.acquireTime != null ? c.fromMicroTime(input.acquireTime) : undefined,
    renewTime: input.renewTime != null ? c.fromMicroTime(input.renewTime) : undefined,
  }}

/** LeaseList is a list of Lease objects. */
export interface LeaseList extends ListOf<Lease> {
  apiVersion?: "coordination.k8s.io/v1";
  kind?: "LeaseList";
};
export function toLeaseList(input: c.JSONValue): LeaseList & c.ApiKind {
  const obj = c.checkObj(input);
  return {
    ...c.assertOrAddApiVersionAndKind(obj, "coordination.k8s.io/v1", "LeaseList"),
    metadata: MetaV1.toListMeta(obj.metadata),
    items: c.readList(obj.items, toLease),
  }}
