name: CI

on:
  push:
    branches: [ main ]
  pull_request: {}

jobs:

  check:
    runs-on: ubuntu-latest
    name: Check w/ ${{ matrix.deno-version }}
    strategy:
      matrix:
        deno-version:
        - v1.41
        - v1.43
        - v1.45
        - canary
      fail-fast: false # run each branch to completion

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Use Deno ${{ matrix.deno-version }}
      uses: denoland/setup-deno@v1
      with:
        deno-version: ${{ matrix.deno-version }}

    # "https" cache: code from the Internet
    # External sources won't change much so we use less precise keys
    - name: Cache https://
      uses: actions/cache@v4
      with:
        path: ~/.cache/deno/deps/https
        key: deno-https/v1-${{ github.sha }}
        restore-keys: deno-https/v1-

    - name: Check generation/mod.ts
      run: time deno check generation/mod.ts

    - name: Check lib/builtin/*/mod.ts
      run: time deno check lib/builtin/*/mod.ts

    - name: Check lib/*/*/mod.ts
      run: time deno check lib/*/*/mod.ts

    - name: Check lib/examples/*.ts
      run: time deno check lib/examples/*.ts

    - name: Test
      run: time deno test

  audit-lib:
    runs-on: ubuntu-latest
    name: Audit ./lib

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Use Deno v1
      uses: denoland/setup-deno@v1
      with:
        deno-version: v1

    - name: Check publish rules
      working-directory: lib
      run: ../with-jsr-deps.sh deno publish --dry-run --allow-dirty
