name: Publish
on:
  push:
    branches:
      - main
    paths:
      - lib/jsr.json

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Publish ./lib

    permissions:
      contents: read
      id-token: write

    steps:
    - uses: denoland/setup-deno@v1

    - uses: actions/checkout@v4

    - name: Publish to JSR
      working-directory: lib
      run: ../with-jsr-deps.sh deno publish --allow-dirty
